### ISSUE TITLE
Lab1 Review by Davide Sferrazza s326619

### ISSUE THREAD

**Issue by FarInHeight** [GNNatan/compint#1]
Hi 👋🏻, Giuseppe Nicola!

First of all, good work! Your code in the notebook is easy to read and that's the most important thing 👍🏻!

I really appreciated your `graph` function. It's a good way to represent a solution you found, especially because it greatly indicates the overlapping *True* values and the taken tiles contained in the solution in the y-axis.

The `search` function you propose is very similar to mine. It's cleanly coded and I didn't find any bug. 

I'd like to point out just a warning. 
At first, you try an $A^\*$ run but you get a solution similar to what you get using a *greedy best-first algorithm*. This is because you use a non-admissible heuristic function. In this way, you cannot guarantee to return a least-cost path solution from the start node to the goal node.
With the use the `rescaled` and `quadratic_rescaled` functions, which return results in $[0, 1]$, instead you get the global optimal solution. This is due to the fact that they are admissible, since they have a value $h(n)$ s.t. $h(n) \le 1 \le h^\*(n)$, where $n$ is not a goal state and $h^*(\cdot)$ is the true cost from $n$ to a goal state.

All this reasoning leads to the conclusion that what you said about the first run of $A^\*$, which I quote below
> With an unitary cost for each edge traversed the result of the greedy best first and A* algorithms reach similar solutions, this is likely due to the fact that the heuristic cost is out of scale in respect to the unitary cost of the arcs

is not quite right, but you were still close to the real reason.

I hope you'll find this review useful and good luck for the next labs 🍀😉!

**Comment by GNNatan** [comment]
Thanks for your feedback! 😊

**Comment by SimoneBorella** [comment]
Hi, Giuseppe!
I'm here referring to the solution of the problem of nim game, finding an optimal agent using an evolutionary strategy.
I like the code, it's pretty clean and well understandable.
I appreciate the proposal of multiple solutions based on both (μ, λ) and (μ + λ) finding good results.
Just some warnings about the code.
I found trying to evaluate the fitness of an individual with the others of the population an interesting thing, but as your results say I don't think it's a good idea.
The fitness function should evaluate how much the individual is able to solve the problem, and making growing the population with a fitness evaluated with growing individuals i think isn't a great choice.
Finally a personal hint is to better show relevant features of your solution with graphs and plots.
Anyway I liked the solutions you realized and I think you did a great job!
I hope you found the review useful and please comment here if you agree with what I understood about your solution.
Good luck for next labs! 🍀
