### ISSUE TITLE
Lab 2 Review by Borella Simone s317774

### ISSUE THREAD

**Issue by SimoneBorella** [GNNatan/compint#2]
Hi, Giuseppe!
I'm here referring to the solution of the problem of nim game, finding an optimal agent using an evolutionary strategy.
I like the code, it's pretty clean and well understandable.
I appreciate the proposal of multiple solutions based on both (μ, λ) and (μ + λ) finding good results.
Just some warnings about the code.
I found trying to evaluate the fitness of an individual with the others of the population an interesting thing, but as your results say I don't think it's a good idea.
The fitness function should evaluate how much the individual is able to solve the problem, and making growing the population with a fitness evaluated with growing individuals i think isn't a great choice.
Finally a personal hint is to better show relevant features of your solution with graphs and plots.
Anyway I liked the solutions you realized and I think you did a great job!
I hope you found the review useful and please comment here if you agree with what I understood about your solution.
Good luck for next labs! 🍀

**Comment by GNNatan** [comment]
Thanks for the feedback!
I found your work very inspiring so for future labs I will definitely look into making some graphs to make my observations clearer, so thanks for the suggestion!
I don't think that the idea of using a fitness function influenced by the population growth is entirely bad, I was trying to create an environment for the individuals to grow and compete with each other. The idea of seeing different strategies rise to the top and then the population adapting to them creating counter-strategies is very fascinating to me and that was what I was trying to implement. Ideally if an optimal strategy (genome) exists the population should converge into it but for some reason what I found in this process was different from what emerged in the "traditional" one. I suspect the way I defined the genes or the problem itself didn't pose themselves well for this kind of approach but I think I will revisit this idea in the future.
