### ISSUE TITLE
Lab9 review by Alberto Foresti s309212

### ISSUE THREAD

**Issue by AlbertoForesti** [GNNatan/compint#3]
Hi, this is my review :D 

Your code is clean and readable, I liked that you tried different approach including non population methods. You explained your choices well, the strategies look well executed and your visualisations are cool.

Just few comments:
- I think that the islands method could benefit from a lower migration rate, both in frequency and migration size, so that islands have more time to develop independent solutions.
- I think that the simulated annealing method could benefit from a different cooling method, since I feel that it allows choosing a worse solution too many times. IMHO this is due to the fact that delta is likely very small since adjacent solutions likely have a similar fitness. Hence you end up with a high probability of choosing a worsening solution.

In general I think you did a very good job and I think that with just a bit more of hyperparameter tuning you could have reached higher heights, but I understand that we have limited resources and time :)

Good luck for the next labs!

**Comment by GNNatan** [comment]
Thanks for the feedback! :smiley:
