### ISSUE TITLE
Peer Review Lab 10

### ISSUE THREAD

**Issue by andrea-ga** [GNNatan/compint#4]
Hi Giuseppe, I'm leaving you some comments about your implementation of the Lab 10, hoping you will find them useful.

- About the training:
Overall I liked your implementation of the agent training. One simple suggestion I can give you is just to try changing in the "value_iteration" function the way of calculating the delta. By reading the code I noticed it's used as a parameter to stop in case there's no more improvements in updating the utility. In this case I would just remove the abs, so making it: `delta = max(delta, utilities_prime[s][0] - utilities[s][0])`. In this way the number of epochs could be reduced without decreasing the win rate.

- About the games evaluation:
I think the final results obtained by playing the games speak by themselves, you did a great job and achieved very good win rate, both in the situation of moving first and of moving second. I liked your idea of letting us test the agent by ourselves.

- About code readability and documentation:
The code is well written and easy to understand. I think the comments give a good explaination of the more complex block of codes, giving an effective reading key. Also the markdown introductions are very useful to understand the approach you used to find the solution strategy. Maybe a small suggestion could be to try adding some graphical rappresentation in order to make the results more "fun" to read.

**Comment by GNNatan** [comment]
Thanks for the feedback!
