### ISSUE TITLE
Peer review lab3

### ISSUE THREAD

**Issue by RoxaneGoffinet** [GNNatan/compint#5]
Hey, nice code. I really appreciate the fact that you tried multiple method in order to get the best results. The laters, also seem satisfactory. However I think that the number of calls to the fitness function could and should be reduced as we want to avoid having too many of them. Looking at the graph we can see that for the first two techniques there is no evolution of fitness after a certain time, maybe implementing an early stop would have save you time and memory. I really liked the idea of the migration phenomenon and didn't thought of it myself, well done, I could also suggest that you try implementing other form of transformation such as double mutation, double crossover, reversion of a part of the genome as maybe it can boost your fitness faster (and maybe even higher). Nonetheless, it is great work

**Comment by RoxaneGoffinet** [comment]
Sorry to be so late to give my review though

**Comment by GNNatan** [comment]
Thanks for the feedback!
